### ISSUE TITLE
bad names

### ISSUE THREAD

**Issue by napo** [DigitalCommonsLab/strade-nomi-confusi#4]
- va fatto un elenco di parole da scartare (ad inizio nome via) come:
   - via
   - v.
   - corso
   - c.so
   - piazza
   - p.
   - piazzetta
   - p.etta
   - viale
   - [ecc..]
altrimenti qualsiasi algoritmo va a calcolare questi casi (e quindi ci sarà sempre un nome "confuso").

**Comment by stefanocudini** [comment]
https://github.com/DigitalCommonsLab/strade-nomi-confusi/blob/master/data/highway_blacklist_name.csv

**Comment by napo** [comment]
ho realizzato che ci sono casi come "Via Vicenza" e "Piazza Vicenza"

**Comment by stefanocudini** [comment]
forse anche Ponte farebbe parte delle badwords..
![screenshot at 2018-04-19 16-25-06](https://user-images.githubusercontent.com/47107/38997723-680e2dae-43ee-11e8-95d2-0a2efe735ef0.png)
